sudo: required
language: generic
services:
 - docker
env:
  matrix:
   - HHVM_VERSION=3.26.3
   - HHVM_VERSION=latest
install:
 - docker pull hhvm/hhvm:$HHVM_VERSION
script:
 - docker run -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION /var/source/.travis.sh
