# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    strategy:
      matrix:
        hhvm: [latest, 4.32-latest]
    runs-on: ubuntu-latest
    container:
      image: hhvm/hhvm:${{ matrix.hhvm }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: bash .github/workflows/setup.sh
      - name: Typecheck
        run: hh_server --check .
      - name: Run tests
        run: vendor/bin/hacktest tests/
